# Generated by Django 4.0.2 on 2023-07-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('trading_date_time', models.DateTimeField(auto_now_add=True)),
                ('trade_value', models.IntegerField()),
            ],
        ),
    ]
